import { Inter, Fira_Code } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import Navbar from '@/components/inicio/ui/Navbar';

const inter = Inter({
	variable: '--font-sans',
	subsets: ['latin'],
});

const fira = Fira_Code({
	variable: '--font-mono',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='es' suppressHydrationWarning>
			<body
				className={`${inter.variable} ${fira.variable} font-sans antialiased`}
			>
				<ThemeProvider>
					<div className='space-y-4'>
						<Navbar />
						<div className='max-w-7xl mx-auto px-4'>{children}</div>
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
