import { Inter, Fira_Code } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import HeroUIToastProvider from '@/components/ui/heroui-toast-provider';
import RootShell from '@/components/ui/root-shell';

const inter = Inter({
	variable: '--font-sans',
	subsets: ['latin'],
});

const fira = Fira_Code({
	variable: '--font-mono',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='es' suppressHydrationWarning>
			<body
				className={`${inter.variable} ${fira.variable} font-sans antialiased`}
			>
				<ThemeProvider attribute='class' defaultTheme='light' enableSystem>
					<RootShell>{children}</RootShell>
					<HeroUIToastProvider />
				</ThemeProvider>
			</body>
		</html>
	);
}
