// Lista de países en español, ordenados: LatAm primero, luego resto del mundo alfabéticamente
const countries = [
  // Latinoamérica y Caribe
  'Argentina',
  'Bolivia',
  'Brasil',
  'Chile',
  'Colombia',
  'Costa Rica',
  'Cuba',
  'Ecuador',
  'El Salvador',
  'Guatemala',
  'Haití',
  'Honduras',
  'Jamaica',
  'México',
  'Nicaragua',
  'Panamá',
  'Paraguay',
  'Perú',
  'Puerto Rico',
  'República Dominicana',
  'Trinidad y Tobago',
  'Uruguay',
  'Venezuela',

  // Europa
  'Alemania',
  'Austria',
  'Bélgica',
  'Bulgaria',
  'Checquia',
  'Chipre',
  'Croacia',
  'Dinamarca',
  'Eslovaquia',
  'Eslovenia',
  'España',
  'Estonia',
  'Finlandia',
  'Francia',
  'Grecia',
  'Hungría',
  'Irlanda',
  'Islandia',
  'Italia',
  'Letonia',
  'Lituania',
  'Luxemburgo',
  'Malta',
  'Mónaco',
  'Montenegro',
  'Noruega',
  'Países Bajos',
  'Polonia',
  'Portugal',
  'Reino Unido',
  'Rumanía',
  'Serbia',
  'Suecia',
  'Suiza',
  'Ucrania',

  // América del Norte
  'Canadá',
  'Estados Unidos',

  // Asia y Oceanía
  'Arabia Saudita',
  'Australia',
  'Bahrein',
  'China',
  'Corea del Sur',
  'Emiratos Árabes Unidos',
  'Filipinas',
  'Hong Kong',
  'India',
  'Indonesia',
  'Israel',
  'Japón',
  'Jordania',
  'Kuwait',
  'Maldivas',
  'Malasia',
  'Nepal',
  'Nueva Zelanda',
  'Omán',
  'Qatar',
  'Singapur',
  'Sri Lanka',
  'Tailandia',
  'Taiwán',
  'Turquía',
  'Vietnam',

  // África
  'Egipto',
  'Etiopía',
  'Kenia',
  'Marruecos',
  'Mozambique',
  'Senegal',
  'Sudáfrica',
  'Tanzania',
  'Túnez',
];

export default countries;
